version: '3.4'

services:
  catalogdb:
    image: mongo:5.0
    container_name: mongodb
    user: root
    restart: always
    ports:
      - "27017:27017" 
    volumes:
      - C:\containers\mongodb:/data/db
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
    #   MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    networks:
      - dev-network

networks:
  dev-network:
    driver: bridge