version: "3.7"

services:
  mssql-server:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: mssql-server
    user: root
    volumes:
      - C:\containers\mssql:/var/opt/mssql/data
    ports: 
      - "1433:1433"
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: ${SQL_PASSWORD}
      MSSQL_PID: ${SQL_PID}
    networks:
      - devlx-network

  sql-pad:
    image: sqlpad/sqlpad
    container_name: sql-pad
    user: root
    volumes: 
        - C:\containers\sqlpad:/var/lib/sqlpad
    ports:
        - "3011:3000"
    environment:
        SQLPAD_ADMIN: ${SQLPAD_ADMIN}
        SQLPAD_ADMIN_PASSWORD: ${SQLPAD_ADMIN_PASSWORD}
        SQLPAD_APP_LOG_LEVEL: info
        SQLPAD_WEB_LOG_LEVEL: warn
        SQLPAD_CONNECTIONS__sqlserverdemo__name: ${SQLPAD_CONNECTIONS__sqlserverdemo__name}
        SQLPAD_CONNECTIONS__sqlserverdemo__driver: sqlserver
        SQLPAD_CONNECTIONS__sqlserverdemo__host: mssql-server
        SQLPAD_CONNECTIONS__sqlserverdemo__database: master
        SQLPAD_CONNECTIONS__sqlserverdemo__username: ${SQL_USER_ID}
        SQLPAD_CONNECTIONS__sqlserverdemo__password: ${SQL_PASSWORD}
    networks:
        - devlx-network
    depends_on: 
        - mssql-server

networks:
  devlx-network:
    driver: bridge